### PR TITLE
V1.1.1

### PR DESCRIPTION
**Pull request by sophie22**
New features:
1. new module added: bcl2fastq. The input file Stats.json is downloaded from the input project
2. option to include custom coverage values calculated at 200, 250, 300, 500 and 1000x
3. option to run app on a single folder (running on a workflow output dir with or without multi-sample workflow is still supported)

Further information about the app/tool and how to incorporate into workflows can be found [here](https://cuhbioinformatics.atlassian.net/wiki/spaces/BT/pages/1410269268/How+to+code+with+MultiQC)

test results from DNAnexus:
single folder [here](https://platform.dnanexus.com/projects/FpG6k2Q4g59bZJ0z15XzByFY/monitor/job/Fyq7qQj4g59ZBx3Q17GxV8K1) and dias run [here](https://platform.dnanexus.com/projects/FpG6k2Q4g59bZJ0z15XzByFY/monitor/job/Fyq7q204g59QJf6GGkbq419Q)

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19)* status: all files reviewed, 7 unresolved discussions (waiting on @sophie22)

___
*[dxapp.json, line 7 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNgoKY4H2eRxDQkvrh:-MNNgoK_7cJh7lEbfbHA:bfmwmp3) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/dxapp.json#L7)):*
> ```JSON
>   "dxapi": "1.0.0",
>   "properties": {
>     "githubRelease": "v1.1.0"
> ```

forgot the github release version change
___
*[Readme.md, line 12 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNiAy41LGYzt6w9NFf:-MNNiAy5DQjsa_7BsSDX:bbmub2k) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/Readme.md#L12)):*
> ```Markdown
> 
> ## What data are required for this app to run?
> * config_file.yaml - A config file specifying which modules to run and the search patterns to recognise QC files for each module
> ```

isn't it recognize ?
___
*[resources/home/dnanexus/calc_custom_coverage.py, line 16 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNuXeN9ofOjzxFfzT_:-MNNuXeN9ofOjzxFfzTa:btyeur2) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/resources/home/dnanexus/calc_custom_coverage.py#L16)):*
> ```Python
> # parse the files' section after ##HISTOGRAM into a dataframe
> # then calculate target bases coverage of each sample and write to a file
> with open("inp/custom_coverage.csv", 'w') as ccc:
> ```

a convention is to call files f when using with open()
___
*[resources/home/dnanexus/calc_custom_coverage.py, line 17 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNuoU77FZxN04psqId:-MNNuoU77FZxN04psqIe:b-fktcdn) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/resources/home/dnanexus/calc_custom_coverage.py#L17)):*
<details><summary><i alt="summary">Quoted 28 lines of code…</i></summary>

> ```
>     ccc.write("Sample,200x,250x,300x,500x,1000x\n")
>     for file in os.listdir(folder):
>         hs_data = pd.read_csv(folder+"/"+file, sep='\t', header=8,
>             usecols=["coverage_or_base_quality", "high_quality_coverage_count"])
>         total = sum(hs_data['high_quality_coverage_count'])
>         # Calculate the coverage at each depth
>         x200x = sum(hs_data.loc[hs_data['coverage_or_base_quality']>=200]['high_quality_coverage_count'])
>         x250x = sum(hs_data.loc[hs_data['coverage_or_base_quality']>=250]['high_quality_coverage_count'])
>         x300x = sum(hs_data.loc[hs_data['coverage_or_base_quality']>=300]['high_quality_coverage_count'])
>         x500x = sum(hs_data.loc[hs_data['coverage_or_base_quality']>=500]['high_quality_coverage_count'])
>         x1000x = sum(hs_data.loc[hs_data['coverage_or_base_quality']>=1000]['high_quality_coverage_count'])
>         # Calculate the %coverage at each depth
>         p200 = x200x/total*100
>         p250 = x250x/total*100
>         p300 = x300x/total*100
>         p500 = x500x/total*100
>         p1000 = x1000x/total*100
>         # Get the sample name
>         fn = file.rstrip('.hsmetrics.tsv')
>         if fn.endswith('.markdup') or fn.endswith('_markdup'):
>             fn = fn[:-8]
>         if fn.endswith('.sorted') or fn.endswith('_sorted'):
>             fn = fn[:-7]
>         if fn.endswith('.duplication') or fn.endswith('_duplication') or fn.endswith('.Duplication') or fn.endswith('_Duplication'):
>             fn = fn[:-12]
>         # Write %coverage at each depth 1 sample/row
>         line = "{},{},{},{},{},{}".format(fn, p200, p250, p300, p500, p1000)
>         ccc.write(line+"\n")
> ```
</details>

I would try and make your code breathe a bit with newlines
Install pycodestyle linter if you're using vscode for pep8
___
*[resources/home/dnanexus/calc_custom_coverage.py, line 41 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNwORcBQ_d1MnixwYQ:-MNNwORdC6zKXIDNMtza:bnswq6h) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/resources/home/dnanexus/calc_custom_coverage.py#L41)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         if fn.endswith('.markdup') or fn.endswith('_markdup'):
>             fn = fn[:-8]
>         if fn.endswith('.sorted') or fn.endswith('_sorted'):
>             fn = fn[:-7]
>         if fn.endswith('.duplication') or fn.endswith('_duplication') or fn.endswith('.Duplication') or fn.endswith('_Duplication'):
>             fn = fn[:-12]
> ```
</details>

Not the best way to do this
I would split the name using _ and get the first element
___
*[src/multiqc.sh, line 28 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNt8MS61wwdSeYyjf6:-MNNt8MTEtmXUyy6QS7v:b-5wu44s) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/src/multiqc.sh#L28)):*
> ```Shell
>             echo "Downloading all files from the given project:/folder"
>             dx download $project:/$ss/* -o ./inp/
>             ss=${ss//\//-}
> ```

I would add a comment (if i understand this correctly, substitute \ with nothing)
I would also store the result in another variable, bash can do funny things when replacing in place
___
*[src/multiqc.sh, line 72 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNuQM8EjuQZApainrE:-MNNuQM8EjuQZApainrF:bw762ux) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/src/multiqc.sh#L72)):*
> ```Shell
>             
>             # Add code that runs the Python script, returns the output file into inp/
>             pip install pandas  # should control which version of pandas is used
> ```

yes you should --> download the version of pandas that you want to use + dependencies and install it locally
eggd_generate_bed installs pandas so you can copy the install bit

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19)* status: all files reviewed, 7 unresolved discussions (waiting on @sophie22 and @Yu-jinKim)

___
*[dxapp.json, line 7 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNgoKY4H2eRxDQkvrh:-MNSZaqN9c1J1eMJoohf:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/dxapp.json#L7)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

forgot the github release version change
</blockquote></details>

Done.
___
*[Readme.md, line 12 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNiAy41LGYzt6w9NFf:-MNSZbvS6SzcMdZSpdDS:b3rx2c1) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/Readme.md#L12)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

isn't it recognize ?
</blockquote></details>

British English uses s, American English uses z
___
*[resources/home/dnanexus/calc_custom_coverage.py, line 16 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNuXeN9ofOjzxFfzT_:-MNSZy2WDOuxRFaqaVMJ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/resources/home/dnanexus/calc_custom_coverage.py#L16)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

a convention is to call files f when using with open()
</blockquote></details>

Done.
___
*[resources/home/dnanexus/calc_custom_coverage.py, line 41 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNwORcBQ_d1MnixwYQ:-MNSafbyDVe7Z9km4e5U:b-vq9o35) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/resources/home/dnanexus/calc_custom_coverage.py#L41)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

> ```
>         if fn.endswith('.markdup') or fn.endswith('_markdup'):
>             fn = fn[:-8]
>         if fn.endswith('.sorted') or fn.endswith('_sorted'):
>             fn = fn[:-7]
>         if fn.endswith('.duplication') or fn.endswith('_duplication') or fn.endswith('.Duplication') or fn.endswith('_Duplication'):
>             fn = fn[:-12]
> ```
Not the best way to do this
I would split the name using _ and get the first element
</blockquote></details>

I know it's not an ideal way of doing this, but since MultiQC is run on output from a range of workflows and the sample naming is not consistent, I couldn't think of a better way.
___
*[src/multiqc.sh, line 28 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNt8MS61wwdSeYyjf6:-MNSgQPS8CMytuuRsQHh:bz0xfex) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/src/multiqc.sh#L28)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

I would add a comment (if i understand this correctly, substitute \ with nothing)
I would also store the result in another variable, bash can do funny things when replacing in place
</blockquote></details>

comment Done
storing result in another variable is done temporarily. But then passed back to $ss as this variable has to be used later on

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19)* status: all files reviewed, 7 unresolved discussions (waiting on @sophie22 and @Yu-jinKim)

___
*[src/multiqc.sh, line 72 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19#-MNNuQM8EjuQZApainrE:-MNSxDTI-o_5CgrW08Xv:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/ee5b1290ed1d573f4aee37b6a5caccc1de7da2a7/src/multiqc.sh#L72)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

yes you should --> download the version of pandas that you want to use + dependencies and install it locally
eggd_generate_bed installs pandas so you can copy the install bit
</blockquote></details>

Done.

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/19)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
