### PR TITLE
MultiQC_v1.1.0

### PR DESCRIPTION
**Pull request by sophie22**
Use dockerised MultiQC_egg, which is based on ewels/MultiQC:v1,9 with modified happy and added sentieon modules.
App now takes a project name and either a single folder or a pair of single and multi sample workflows to extract QC tool output files and feed them in a single input folder to MultiQC. Input folder is renamed to project-single_sample without '002_' and '_clinicalgenetics' and is also shown on the report for easier identification of the data in the report.

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18)* status: all files reviewed, 5 unresolved discussions (waiting on @sophie22)

___
*[Readme.md, line 42 at r1](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18#-MI-ksiQ8adCF75syBk0:-MI-ksiQ8adCF75syBk1:bafzt37) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/705e39716fa78cc2ed84fab5bb6824885b2d7251/Readme.md#L42)):*
> ```
> A config file is used to search for files with specific name patterns, which are downloaded if found.
> ```
Can I suggest changing this to:
Searches for files with specific name patterns (defined in the config file), which are downloaded if found
___
*[Readme.md, line 43 at r1](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18#-MI-lCWu93why2YE9WwN:-MI-lCWu93why2YE9WwO:b-ouk49l) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/705e39716fa78cc2ed84fab5bb6824885b2d7251/Readme.md#L43)):*
> ```
> directory
> ```
directories?
since you can have multiple QC app directories
___
*[Readme.md, line 44 at r1](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18#-MI-lQoc-AUqmGAok2u8:-MI-lQoc-AUqmGAok2u9:btrujnj) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/705e39716fa78cc2ed84fab5bb6824885b2d7251/Readme.md#L44)):*
> ```
> SNP and indel values
> ```
SNP and indel precision/recall values
___
*[src/multiqc.sh, line 18 at r1](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18#-MI-lvP39NZGtYGAbEZC:-MI-lvP39NZGtYGAbEZD:bv2o6d6) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/705e39716fa78cc2ed84fab5bb6824885b2d7251/src/multiqc.sh#L18)):*
> ```
>  # xargs strips leading/trailing whitespace from input strings submitted by the user
> ```
Can we shift this line to just before the first instance of this being used on line 11
___
*[src/multiqc.sh, line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18#-MI-n-v2ApazI3EEwEiu:-MI-n-v3C5J2GWG5ARrb:b-qusljg) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/705e39716fa78cc2ed84fab5bb6824885b2d7251/src/multiqc.sh#L56)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>   # Remove 002_ from the beginning of the project name, if applicable
>     if [[ "$project" == 002_* ]]; then
>         project=${project:4}
>     fi
>     # Remove '_clinicalgenetics' from the end of the project name, if applicable
>     if [[ "$project" == *_clinicalgenetics ]]; then
>         project=${project%_clinicalgenetics}
>         # project=$p
>     fi
> ```
</details>

What's the purpose of stripping the pre/suffixes?

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18)* status: all files reviewed, 6 unresolved discussions (waiting on @sophie22)

___
*[src/multiqc.sh, line 15 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18#-MI05yZk98KkWS3Ia4_C:-MI05yZk98KkWS3Ia4_D:bzeqn0h) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/eec39887b58186a488d4bdbb06f4b5f60a48bdc8/src/multiqc.sh#L15)):*
> ```
> ····
> ```
Whitespace!

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18)* status: all files reviewed, 6 unresolved discussions (waiting on @mattgarner and @sophie22)

___
*[Readme.md, line 42 at r1](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18#-MI-ksiQ8adCF75syBk0:-MI-zawJDiw7V-XpXbgM:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/705e39716fa78cc2ed84fab5bb6824885b2d7251/Readme.md#L42)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> A config file is used to search for files with specific name patterns, which are downloaded if found.
> ```
Can I suggest changing this to:
Searches for files with specific name patterns (defined in the config file), which are downloaded if found
</blockquote></details>

Done.
___
*[Readme.md, line 43 at r1](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18#-MI-lCWu93why2YE9WwN:-MI-zeLS7AoavwQogW7D:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/705e39716fa78cc2ed84fab5bb6824885b2d7251/Readme.md#L43)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> directory
> ```
directories?
since you can have multiple QC app directories
</blockquote></details>

Done.
___
*[Readme.md, line 44 at r1](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18#-MI-lQoc-AUqmGAok2u8:-MI-zmYj2uG5U57ebcd9:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/705e39716fa78cc2ed84fab5bb6824885b2d7251/Readme.md#L44)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> SNP and indel values
> ```
SNP and indel precision/recall values
</blockquote></details>

Done.
___
*[src/multiqc.sh, line 18 at r1](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18#-MI-lvP39NZGtYGAbEZC:-MI0-2BP1bMzLdeyf6Nd:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/705e39716fa78cc2ed84fab5bb6824885b2d7251/src/multiqc.sh#L18)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>  # xargs strips leading/trailing whitespace from input strings submitted by the user
> ```
Can we shift this line to just before the first instance of this being used on line 11
</blockquote></details>

Done.
___
*[src/multiqc.sh, line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18#-MI-n-v2ApazI3EEwEiu:-MI0-2xF2bpqQEWw_vu0:bodhuvs) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/705e39716fa78cc2ed84fab5bb6824885b2d7251/src/multiqc.sh#L56)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>   # Remove 002_ from the beginning of the project name, if applicable
>     if [[ "$project" == 002_* ]]; then
>         project=${project:4}
>     fi
>     # Remove '_clinicalgenetics' from the end of the project name, if applicable
>     if [[ "$project" == *_clinicalgenetics ]]; then
>         project=${project%_clinicalgenetics}
>         # project=$p
>     fi
> ```
What's the purpose of stripping the pre/suffixes?
</blockquote></details>

the file names can be very lengthy and I thought that 002 and clinicalgenetics doesn't carry much information

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/multiqc.sh, line 15 at r2](https://reviewable.io/reviews/eastgenomics/eggd_multiqc/18#-MI05yZk98KkWS3Ia4_C:-MI3CtUwD5bLu7Eo4_2-:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_multiqc/blob/eec39887b58186a488d4bdbb06f4b5f60a48bdc8/src/multiqc.sh#L15)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ····
> ```
Whitespace!
</blockquote></details>

Done

**Pull request merged**
